---
abstract: 'very simplicistic signatures for Perl < 5.20'
author:
  - 'Max Maischein <corion@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.24, CPAN::Meta::Converter version 2.143240'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Filter-signatures
no_index:
  directory:
    - t
    - inc
requires:
  Filter::Simple: '0.91'
  perl: '5.006'
resources:
  repository: git://github.com/Corion/filter-signatures.git
version: '0.09'
